# Generated by Django 5.2.6 on 2025-09-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_avaliacao_nomemusica_alter_avaliacao_estrelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=80)),
                ('musica', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliações'},
        ),
    ]
